var webpack = require('webpack');
var path = require('path');

/**
 * see http://webpack.github.io/docs/configuration.html
 * for webpack configuration options
 */
module.exports = {
  // enable source-maps
  devtool: 'source-map',

  // needed "stub" out these modules requried by Joi
  node: {
    net: "empty",
    fs: "empty",
    dns: "empty"
  },

  // 'context' sets the directory where webpack looks for module files you list in
  // your 'require' statements
  context: path.join(__dirname, '..', '/app/webpack_javascripts'),

  // 'entry' specifies the entry point, where webpack starts reading all
  // dependencies listed and bundling them into the output file.
  // The entrypoint can be anywhere and named anything - here we are calling it
  // '_application' and storing it in the 'javascripts' directory to follow
  // Rails conventions.
  //entry: './app/webpack_javascripts/authorwatch/app.js',
  entry: {
    vendor: [
      'react',
      'flux',
      'immutable'
    ],
    app: [
      './authorwatch/app.js'
    ]
  },

  // 'output' specifies the filepath for saving the bundled output generated by
  // wepback.
  // It is an object with options, and you can interpolate the name of the entry
  // file using '[name]' in the filename.
  // You will want to add the bundled filename to your '.gitignore'.
  output: {
    filename: '[name]_wp_bundle.js',
    // We want to save the bundle in the Asset Pipleine directory as the other JS.
    path: path.join(__dirname, '..', '/app/assets/javascripts')
  },

  externals: {
    // require("jquery") is external and available
    //  on the global var jQuery
    "jquery": "jQuery"
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor_wp_bundle.js'),
    new webpack.NoErrorsPlugin()
  ],

  resolve: {
    extensions: ['', '.js', '.jsx']
  },

  // The 'module' and 'loaders' options tell webpack to use loaders.
  // @see http://webpack.github.io/docs/using-loaders.html
  module: {
    loaders: [
      {
        // Pattern to match only files with the '.js' or '.jsx' extension.
        // This tells the loader to only run for those files.
        test: /\.jsx?$/,
        loaders: ['babel-loader'],
        exclude: /node_modules/
      }
    ]
  }
};
